# Generated by Django 4.1.13 on 2024-05-31 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'medical_tests',
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=255)),
                ('doctor_id', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('reason', models.CharField(max_length=255)),
                ('symptoms', models.CharField(max_length=255)),
                ('first_diagnosis', models.CharField(max_length=255)),
                ('final_diagnosis', models.CharField(max_length=255)),
                ('treatment_plan', models.CharField(max_length=255)),
                ('note', models.TextField()),
                ('medical_tests', models.ManyToManyField(to='medical_record.medicaltest')),
            ],
            options={
                'db_table': 'medical_records',
            },
        ),
    ]
