# Generated by Django 4.1.13 on 2024-05-31 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room_management_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientBed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
            ],
            options={
                'db_table': 'patients_beds',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'types',
            },
        ),
        migrations.RemoveField(
            model_name='bed',
            name='hospital_room',
        ),
        migrations.AddField(
            model_name='clinic',
            name='doctor_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterModelTable(
            name='bed',
            table='beds',
        ),
        migrations.AlterModelTable(
            name='clinic',
            table='clinics',
        ),
        migrations.AlterModelTable(
            name='department',
            table='departments',
        ),
        migrations.DeleteModel(
            name='HospitalRoom',
        ),
        migrations.AddField(
            model_name='room',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='room_management_model.department'),
        ),
        migrations.AddField(
            model_name='room',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_management_model.type'),
        ),
        migrations.AddField(
            model_name='patientbed',
            name='bed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_beds', to='room_management_model.bed'),
        ),
        migrations.AddField(
            model_name='bed',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='room_management_model.room'),
        ),
    ]
