# Generated by Django 4.1.13 on 2024-05-31 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyProject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.TextField(max_length=255)),
                ('street', models.TextField(max_length=255)),
                ('district', models.TextField(max_length=255)),
                ('city', models.TextField(max_length=255)),
                ('province', models.TextField(max_length=255)),
                ('country', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MedicalSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(max_length=255)),
                ('note', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacyProject.address')),
            ],
        ),
        migrations.DeleteModel(
            name='Pharmacy',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='total_amount',
            new_name='total_price',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_number',
        ),
        migrations.AddField(
            model_name='invoice',
            name='patient_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='staff_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='MedicalSupply',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacyProject.producer'),
        ),
        migrations.AddField(
            model_name='InvoiceDetail',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacyProject.invoice'),
        ),
        migrations.AddField(
            model_name='InvoiceDetail',
            name='medical_supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacyProject.medicalsupply'),
        ),
    ]
