# Generated by Django 4.1.13 on 2024-05-31 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyProject', '0002_address_invoicedetail_medicalsupply_producer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.AlterModelTable(
            name='address',
            table='addresses',
        ),
        migrations.AlterModelTable(
            name='invoice',
            table='invoices',
        ),
        migrations.AlterModelTable(
            name='invoicedetail',
            table='invoice_details',
        ),
        migrations.AlterModelTable(
            name='medicalsupply',
            table='medical_supplies',
        ),
        migrations.AlterModelTable(
            name='producer',
            table='producers',
        ),
        migrations.AddField(
            model_name='medicalsupply',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pharmacyProject.category'),
            preserve_default=False,
        ),
    ]
